book_report/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.http import HttpResponseRedirect

urlpatterns = [
    url(r'^$', lambda r: HttpResponseRedirect('books/')),
    url(r'^books/', include('books.urls', namespace="books")),
    url(r'^admin/', include(admin.site.urls)),
]

books/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    # ex: /books/
    url(r'^$', views.index, name='index'),
    # ex: /books/5/
    url(r'^(?P<book_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'^new/(?P<book_id>[0-9]+)/$', views.new_review, name='new-review'),
    url(r'^used/(?P<book_id>[0-9]+)/$', views.used_review, name='used-review'),
    # ex: /books/5/results/
    url(r'^(?P<book_id>[0-9]+)/results/$', views.results, name='results'),
    # ex: /books/5/vote/
    url(r'^(?P<book_id>[0-9]+)/list/', views.list_book, name='list'),
    url(r'^charts/(?P<book_id>[0-9]+).png$', views.simple_chart, name='chart'),
    url(r'^charts/review/(?P<book_id>[0-9]+)-(?P<condition>[0-9]).png$', views.book_chart, name='book-chart'),
    url(r'^(?P<book_id>[0-9]+)/compare/$', views.compare, name='compare'),
    url(r'^(?P<book_id>[0-9]+)/update/$', views.update, name='update'),
    url(r'^search$', views.search, name='search'),
    url(r'^affiliate$', views.affiliate, name='affiliate'),
    url(r'^warning$', views.it, name='it'),
    url(r'^(?P<slug>[-\w\d]+),(?P<id>\d+)/$', view=views.comparison, name='comparison'),
    url(r'^(?P<slug>[-\w\d]+),(?P<id>\d+)/report/$', view=views.report, name='report'),

]

books/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.template import RequestContext, loader
from django.shortcuts import get_object_or_404, render
from django.db.models import Q, Max, Count, F
from django.core.urlresolvers import reverse
import search
from embed_video.backends import detect_backend

import states, aws_config

from .models import Book, InventoryBook, Price, BookScore, SalesRank, Comparison

from .charts import simple, book_image

review_strategy='ALL'

review_strategy='LOW'


def index(request):
    compare_list = Comparison.objects.filter(top_find=True).order_by('rank')
    my_video = detect_backend('https://www.youtube.com/watch?v=nojaxvETShg&t=26s')
    context =  {
        'compare_list': compare_list,
        'my_video' : my_video,
        
    }
    return render(request, 'books/index.html', context)
    
def affiliate(request):
    compare_list = Comparison.objects.filter(top_find=True).order_by('rank')
    context =  {
        'compare_list': compare_list,
        
    }
    return render(request, 'books/affiliate.html', context)
        
def it(request):
    compare_list = Comparison.objects.filter(top_find=True).order_by('rank')
    context =  {
        'compare_list': compare_list,
        
    }
    return render(request, 'books/it.html', context)
import re

from django.db.models import Q

def normalize_query(query_string,
                    findterms=re.compile(r'"([^"]+)"|(\S+)').findall,
                    normspace=re.compile(r'\s{2,}').sub):
    ''' Splits the query string in invidual keywords, getting rid of unecessary spaces
        and grouping quoted words together.
        Example:
        
        >>> normalize_query('  some random  words "with   quotes  " and   spaces')
        ['some', 'random', 'words', 'with quotes', 'and', 'spaces']
    
    '''
    return [normspace(' ', (t[0] or t[1]).strip()) for t in findterms(query_string)] 

def get_query(query_string, search_fields):
    ''' Returns a query, that is a combination of Q objects. That combination
        aims to search keywords within a model by testing the given search fields.
    
    '''
    query = None # Query to search for every search term        
    terms = normalize_query(query_string)
    for term in terms:
        or_query = None # Query to search for a given term in each field
        for field_name in search_fields:
            q = Q(**{"%s__icontains" % field_name: term})
            if or_query is None:
                or_query = q
            else:
                or_query = or_query | q
        if query is None:
            query = or_query
        else:
            query = query & or_query
    return query

def search(request):
    query_string = ''
    found_entries = None
    if ('q' in request.GET) and request.GET['q'].strip():
        query_string = request.GET['q']
        
        entry_query = get_query(query_string, ['title', 'author','isbn', 'isbn13'])
        
        found_entries = list(Book.objects.filter(track=True).filter(entry_query).order_by('-publicationDate'))


    return render(request, 'books/search.html',
                          { 'query_string': query_string, 'found_entries': found_entries })

def comparison(request, slug, id):
    comparison = get_object_or_404(Comparison, pk=id)   
    current_book  =  get_object_or_404(Book, pk=comparison.current_edition.id)
    previous_book = comparison.previous_edition                    
    previous_book = None
    previous_price = None
    previous_price_used=None
    previous_book = current_book.get_previous_edition()
    current_price = Price.objects.filter(condition='5', book=current_book).order_by('-price_date')
    if len(current_price) > 0:
        current_price=current_price[0]
    else:
        current_price=None
        
    current_price_used = Price.objects.filter(condition='0', book=current_book).order_by('-price_date')
    if len(current_price_used) > 0:
        current_price_used=current_price_used[0]
    else:
        current_price_used=None

    if previous_book:
        previous_price_used = Price.objects.filter(condition='0', book=previous_book).order_by('-price_date')
        if len(previous_price_used) > 0:
            previous_price_used=previous_price_used[0]
        previous_price = Price.objects.filter(condition='5', book=previous_book).order_by('-price_date')
        if len(previous_price) > 0:
            previous_price=previous_price[0]
        
    context =  {
        'compare': comparison,
        'current_book': current_book,
        'previous_book': previous_book,
        'current_price': current_price,
        'previous_price': previous_price,
        'current_price_used': current_price_used,
        'previous_price_used': previous_price_used,
        'affiliate': aws_config.AWS_USER,
    }
    return render(request, 'books/compare.html', context)

def report(request, slug, id):
    comparison = get_object_or_404(Comparison, pk=id)   
    current_book  =  get_object_or_404(Book, pk=comparison.current_edition.id)
    previous_book = comparison.previous_edition                    
    previous_book = None
    previous_price = None
    previous_price_used=None
    previous_book = current_book.get_previous_edition()
    current_price = Price.objects.filter(condition='5', book=current_book).order_by('-price_date')
    if len(current_price) > 0:
        current_price=current_price[0]
    else:
        current_price=None
        
    current_price_used = Price.objects.filter(condition='0', book=current_book).order_by('-price_date')
    if len(current_price_used) > 0:
        current_price_used=current_price_used[0]
    else:
        current_price_used=None

    if previous_book:
        previous_price_used = Price.objects.filter(condition='0', book=previous_book).order_by('-price_date')
        if len(previous_price_used) > 0:
            previous_price_used=previous_price_used[0]
        previous_price = Price.objects.filter(condition='5', book=previous_book).order_by('-price_date')
        if len(previous_price) > 0:
            previous_price=previous_price[0]
        
    context =  {
        'compare': comparison,
        'current_book': current_book,
        'previous_book': previous_book,
        'current_price': current_price,
        'previous_price': previous_price,
        'current_price_used': current_price_used,
        'previous_price_used': previous_price_used,
        'affiliate': aws_config.AWS_USER,
    }
    return render(request, 'books/report.html', context)
        
def compare(request, book_id):
    book = get_object_or_404(Book, pk=book_id)
    if not book.is_current_edition():
        current_book = book.current_edition
    else:
        current_book = book
    comparison = Comparison.objects.get(current_edition=current_book.id)
    previous_book = None
    previous_price=None
    previous_psrice_used=None
    previous_book = current_book.get_previous_edition()
    current_price = Price.objects.filter(condition='5', book=current_book).order_by('-price_date')
    if len(current_price) > 0:
        current_price=current_price[0]
    else:
        current_price=None
        
    current_price_used = Price.objects.filter(condition='0', book=current_book).order_by('-price_date')
    if len(current_price_used) > 0:
        current_price_used=current_price_used[0]
    else:
        current_price_used=None

    if previous_book:
        previous_price_used = Price.objects.filter(condition='0', book=previous_book).order_by('-price_date')
        if len(previous_price_used) > 0:
            previous_price_used=previous_price_used[0]
        previous_price = Price.objects.filter(condition='5', book=previous_book).order_by('-price_date')
        if len(previous_price) > 0:
            previous_price=previous_price[0]
        
    context =  {
        'compare': comparison,
        'current_book': current_book,
        'previous_book': previous_book,
        'current_price': current_price,
        'previous_price': previous_price,
        'current_price_used': current_price_used,
        'previous_price_used': previous_price_used,
        'affiliate': aws_config.AWS_USER,
    }
    return render(request, 'books/compare.html', context)
    
def getPrevAndNext(group, item):
    foundit = False
    prev = item
    nxt = item
    for x in group:
        if foundit:
            nxt = x
            break
        if x == item:
            foundit = True
        else:
            prev = x
    return prev, nxt

    
def detail(request, book_id):
    book = get_object_or_404(InventoryBook, pk=book_id)
    if book.list_condition == '5':
        condition = '5'
    else:
        condition = '0'
    score = book.book.get_bookscore()
    price_score  = score.getPriceScore(condition)
    price = Price.objects.filter(book=book.book, condition=condition).latest('price_date')
    rank = SalesRank.objects.filter(book=book.book).latest('rank_date')
    if review_strategy == 'ALL':
        listed_book_list = InventoryBook.objects.filter(       \
            (Q(book__bookscore__pricescore__condition=F('list_condition')) | \
            Q(book__bookscore__pricescore__condition='0') & ~Q(list_condition='5')))\
            .filter(status='LT') \
            .order_by('-book__bookscore__pricescore__current_price_score')
    else:
        listed_book_list = InventoryBook.objects.filter(       \
            (Q(book__bookscore__pricescore__condition=F('list_condition')) | \
            Q(book__bookscore__pricescore__condition='0') & ~Q(list_condition='5')))\
            .filter(status='LT',listing_strategy=review_strategy) \
            .order_by('-book__bookscore__pricescore__current_price_score')
    prev, nxt = getPrevAndNext(listed_book_list, book)
    


    return render(request, 'books/detail.html', {'book': book, 'score': score, 'price_score': price_score, 'price': price, 'rank': rank, 'prev': prev, 'next': nxt})

 
    
def update(request, book_id):

books/views/charts.py
# file charts.py
def simple(request):
    import random
    import django
    import datetime
    
    from matplotlib.backends.backend_agg import FigureCanvasAgg as FigureCanvas
    from matplotlib.figure import Figure
    from matplotlib.dates import DateFormatter

    fig=Figure()
    ax=fig.add_subplot(111)
    x=[]
    y=[]
    now=datetime.datetime.now()
    delta=datetime.timedelta(days=1)
    for i in range(10):
        x.append(now)
        now+=delta
        y.append(random.randint(0, 1000))
    ax.plot_date(x, y, '-')
    ax.xaxis.set_major_formatter(DateFormatter('%Y-%m-%d'))
    fig.autofmt_xdate()
    canvas=FigureCanvas(fig)
    response=django.http.HttpResponse(content_type='image/png')
    canvas.print_png(response)
    return response

books/templates/books/__base.html
{% load staticfiles i18n %}
{% load analytical %}
<!DOCTYPE html>
<html lang="en">
  <head>
    {% analytical_head_top %}
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        {% block meta_tags %}{% endblock %}
        <title>
            {% block title %}{% trans "Which Edition" %}{% endblock %}
        </title>
        {% block stylesheets %}
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
            <link rel="stylesheet" href="{% static "books/style.css" %}" type="text/css" /> 
        {% endblock %}
        {% block javascript %}
            <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
            <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
        {% endblock %}
        {% block extra_head %}{% endblock %}
        {% analytical_head_bottom %}
    </head>
    <body>
        {% analytical_body_top %}
        <!--<header class="navbar navbar-fixed-top"> -->

            {% include "books/_navigation.html" %}
            {% block alert %}{% endblock %}        <!--</header>-->
        <div id="main" role="main">
            <div class="container">
                {% block content %}
                {% endblock %}
            </div>
            
        </div>
        {% include "books/_footer.html" %} 
        {% analytical_body_bottom %}
    </body>
</html>

books/templates/books/__l_75_25.html
{% extends "books/__base.html" %}

{% block content %}
    <div class="row">
        <div class="col-md-8">
            {% block main_col %}{% endblock %}
        </div>
        <div class="col-md-4">
            {% block side_col%}{% endblock %}
        </div>
    </div>
        
{% endblock %}

books/templates/books/__l_left_sidebar.html
{% extends "gazette/__base.html" %}

{% block content %}
    <div class="row">
        <div class="span4">
            {% block side_col %}{% endblock %}
        </div>
        <div class="span8">
            {% block main_col %}{% endblock %}
        </div>
    </div>
{% endblock %}

books/templates/books/__l_one_col.html
{% extends "books/__base.html" %}

{% block content %}
    <div class="row">
        <div class="col">
            {% block main_col %}{% endblock %}
        </div>
    </div>
{% endblock %}

books/templates/books/_amazon_affiliate_disclosure.html
We are a participant in the Amazon Services LLC Associates Program, an affiliate advertising program designed to provide a means for us to earn fees by linking to Amazon.com and affiliated sites.

books/templates/books/_amazon_data_disclosure.html
CERTAIN CONTENT THAT APPEARS ON THIS SITE COMES FROM AMAZON SERVICES LLC. THIS CONTENT IS PROVIDED ‘AS IS’ AND IS SUBJECT TO CHANGE OR REMOVAL AT ANY TIME.

books/templates/books/_book_compare.html
{% load staticfiles %}
{% load humanize %}
       {% if book %}
       
<div class="panel panel-default">
  <!-- Default panel contents -->
  <div class="panel-heading">{{ edition_type }} Edition</div>
  <div class="panel-body">
        
          <!-- Default panel contents -->
          <div class="row">
          <div class="col-md-6 {{opposite}}">
            <div class="panel panel-default ">
              <!-- Default panel contents -->
              <div class="panel-heading ">Price <small><small><small>as of {{ price_new.price_date }} <a href="#"  data-toggle="tooltip" title="{% include 'books/_amazon_price_disclosure.html' %}">Details</a></small></small></small></p></div>
              <div class="panel-body">
                <ul class="list-group">
                    <li class="list-group-item">New: <a href="http://amazon.com/dp/{{book.asin}}?tag={{ affiliate }}">${{ price_new.price }} 
                        {% if edition_type == 'Previous' and compare.previous_better_new%}
                            <img src='{% static "books/Logo.png" %}' height='30px'> <p>Save ${{compare.difference_new|floatformat:"2"|intcomma}} ({{compare.savings_new|floatformat:"0"|intcomma}}%)</p>
                        {% elif edition_type == 'Previous'%}
                            <img src='{% static "books/Logo.png" %}' height='30px'> <p>Save ${{compare.difference_new|floatformat:"2"|intcomma}} ({{compare.savings_new|floatformat:"0"|intcomma}}%)</p>
                        {% endif %}</a></li>
                    <li class="list-group-item">Used: <a href="http://amazon.com/dp/{{book.asin}}?tag={{ affiliate }}">${{ price_used.price }}
                            {% if edition_type == 'Previous' and compare.previous_better_used%}
                            <img src='{% static "books/Logo.png" %}' height='30px'> <p>Save ${{compare.difference_used|floatformat:"2"|intcomma}} ({{compare.savings_used|floatformat:"0"|intcomma}}%)</p>
                        {% elif edition_type == 'Previous'%}
                            <img src='{% static "books/Logo.png" %}' height='3s0px'> <p>Save ${{compare.difference_used|floatformat:"2"|intcomma}} ({{compare.savings_used|floatformat:"0"|intcomma}}%)</p>
                        {% endif %} </a> </li>
                
            
                </ul>
              </div>
            </div>
          </div>
          <div class="col-md-6 {{edition_type}}">
                <figure >
                  <a href="http://amazon.com/dp/{{book.asin}}?tag={{ affiliate }}"><img class='compare' src="
                    {% if book.largeImageLink %}
                        {{ book.largeImageLink }}
                    {% else %}
                        {% if book.mediumImageLink  %}
                            {{ book.mediumImageLink }}
                        {% else %}
                             {{ book.imageLink }}
                        {% endif %}
                    {% endif %}
                    " alt="{{ book.title }}" ></a>
                  <figcaption class='{{edition_type}}'><strong>{{ book.title }}</strong> (Edition: {{book.edition}})</figcaption>
          
        </figure> 
        <div ><a href="http://amazon.com/dp/{{book.asin}}?tag={{ affiliate }}"><img src='{% static "books/buy4.gif" %}'></a> (Affiliate link)</div>

          </div>
        </div>
    
     
        <div> <p>  &nbsp;</p> </div>
        <div class="panel panel-default">
          <!-- Default panel contents -->
          <div class="panel-heading">Details</div>
          <div class="panel-body">
            <ul class="list-group">
                <li class="list-group-item">ISBN: {{ book.isbn13 }}</li>
                <li class="list-group-item">Published: {{ book.publicationDate }}</li>
                <li class="list-group-item">Pages: {{ book.page_count }}</li>
                <li class="list-group-item">New Price: ${{ price_new.price }} <small>as of {{ price_new.price_date }} <a href="#"  data-toggle="tooltip" title="{% include 'books/_amazon_price_disclosure.html' %}">Details</a></small> </li>
                <li class="list-group-item">Used Price: ${{ price_used.price }}  <small>as of {{ price_used.price_date }} <a href="#"  data-toggle="tooltip" title="{% include 'books/_amazon_price_disclosure.html' %}">Details</a></small></li>
            
            
                </ul>
          </div>
        </div>
          
        <div class="panel panel-default">
          <!-- Default panel contents -->
          <div class="panel-heading">Publisher Information</div>
          <div class="panel-body">
            {{ book.description | safe }}
          </div>
        </div>

  </div>
</div>
       
        {% else %}
            <div>No {{ edition_type }} edition information in our database!</div>
        {% endif %} 
    

books/templates/books/_compare_list.html
{% load staticfiles %}
{% load humanize %}
<div class="panel panel-default">
  <!-- Default panel contents -->
  <div class="panel-heading">Today's Biggest Savings</div>
  <div class="panel-body">
    <p>Below are a list of books and how much you would save if you purchased the previous edition instead of the newest edition.</p>
  </div>

  <!-- Table -->
  <table class="table">
      <thead><tr><th>Title</th><th>Savings New</th><th>Savings Used</th></tr></thead>

      <tbody>
                {% for compare in compare_list %}
    <tr>
         <td> <a href="{% url 'books:comparison' compare.current_edition.slug  compare.id %}"><img src='{{compare.current_edition.imageLink}}' class='search' > {{ compare.current_edition.title }}</a></td>
         <td>${{ compare.difference_new|floatformat:"2"|intcomma }} ({{compare.savings_new|floatformat:"0"|intcomma}}%)</td>
         <td>${{ compare.difference_used|floatformat:"2"|intcomma }} ({{compare.savings_used|floatformat:"0"|intcomma}}%)</td></tr>
    {% endfor %}
    </tbody>
  </table>
</div>

books/templates/books/_footer.html
{% load staticfiles %}
<div class='row'><div class='col-md-10'>{% include 'books/_amazon_data_disclosure.html' %}</div></div>

books/templates/books/_navigation.html
{% load staticfiles %}

<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a href="/"><img src="{% static 'books/we_banner.png' %}" height="70" > </a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="/">Home <span class="sr-only">(current)</span></a></li>
        <!--
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li> -->
      </ul>
      <form class="navbar-form navbar-right" method="get" action="/books/search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Title, Author or ISBN"  name="q" id="id_q" value="{{ query_string }}">
        </div>
        <button type="submit" class="btn btn-default">Search</button>
      </form>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

books/templates/books/affiliate.html
{% extends "books/__l_75_25.html" %}

{% block title %}Affiliate Disclosure | {{ block.super }}{% endblock %}



{% block main_col %}
    
    {% include "books/_affiliate.html"  %}
{% endblock %}

{% block side_col %}
    {% include "books/_compare_list.html"  %}
{% endblock %}


<!--<header><img id='banner' src="% static "books/we_banner.png" %" alt="WHICH EDITION"/>
WhichEdition Header - {{ current_book.title }}</header> -->

books/templates/books/detail.html
{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'books/style.css' %}" />

<h3>{{ book.book.title }} - {{ book.list_condition }} - {{ book.listing_strategy }} - {{book.book.asin}}</h3>
{% if book.status == 'RQ' %}
    <form action="{% url 'books:list' book.id %}" method="post">
        {% csrf_token %}
        <input type="text" name="Price" id="original_ask_price" value="{{ book.original_ask_price}}" />
        <input type="text" name="Condition" id="list_condition" value="{{ book.list_condition}}" />
        
 
        <input type="submit" value="List" />
        </form>
{% endif %}
{% if book.status == 'LT' %}
        <p><a href="{% url 'books:index' %}">Home</a> - <a href="{% url 'books:detail' prev.id %}">Prev</a> - <a href="{% url 'books:detail' next.id %}">Next</a> - <a href="http://camelcamelcamel.com/product/{{book.book.asin}}">Camel</a>
         - <a href="../../admin/books/book/{{ book.book.id }}">Edit</a>  - <a href="http://amazon.com/gp/offer-listing/{{ book.book.asin }}">Amazon</a></p>
        <table>
                <tr><td>Purchase Price: ${{ book.purchase_price }}</td><td>Current Sales Rank: {{rank.rank}}</td><td>{{rank.rank_date}}</td><td>Current Edition: {{book.book.is_current_edition}}</td></tr>
                <tr><td>Current Low Price: ${{price.price}}</td><td>Sell Score: {{price_score.current_price_score}}</td><td>My Price: ${{ book.last_ask_price }}</td><td>Previous Edition: {{book.book.is_previous_edition}}</td></tr>
                <tr><td>High Sale Price: ${{price_score.highest_sold_price.price}}</td><td>High Sale Date: {{price_score.highest_sold_price.price_date}}</td><td>My Price: ${{ book.last_ask_price }}</td></tr>
        </table>
        <img src="{% url 'books:chart' book.id %}" width="400" height="300"/>
    <form action="{% url 'books:list' book.id %}" method="post">
        {% csrf_token %}
        <input type="text" name="Price" id="original_ask_price" value="{{ book.original_ask_price}}" />
        <input type="text" name="Condition" id="list_condition" value="{{ book.list_condition}}" />
        <input type="radio" name="strategy" value="HHI" {% if book.listing_strategy == 'HHI' %}checked {% endif %}>Hold High<br>
        <input type="radio" name="strategy" value="LOW" {% if book.listing_strategy == 'LOW' %}checked {% endif %}> Chase Low Price<br>
        <input type="radio" name="strategy" value="39D" {% if book.listing_strategy == '30D' %}checked {% endif %}> 30-Day Drop<br>  
        
 
        <input type="submit" value="List" />
        </form>
        
        
{% endif %}
            <form method="post" action="{% url 'books:update' book.book.id %}">
                {% csrf_token %}
                <input type="hidden" name="q" id="id_q" value="{{ book.book.id }}"/>
                <input type="submit" value="Update"/>
            </form>
<ul>

</ul>

books/templates/books/review.html
{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'books/style.css' %}" />
Hi review.html
<h3>{{ book.title }} - {{condition}}</h3>

        <p><a href="{% url 'books:index' %}">Home</a> - 
        {% if condition == '5' %}
        <a href="{% url 'books:new-review' prev.id %}">Prev</a> - <a href="{% url 'books:new-review' next.id %}">Next</a> - 
        {% else %}
        <a href="{% url 'books:used-review' prev.id %}">Prev</a> - <a href="{% url 'books:used-review' next.id %}">Next</a> - 
        {% endif %}
        <a href="http://camelcamelcamel.com/product/{{book.asin}}">Camel</a>
         - <a href="../../admin/books/book/{{ book.id }}">Edit</a>  - <a href="http://amazon.com/gp/offer-listing/{{ book.asin }}">Amazon</a></p>
        <table>
                <tr><td>Current Sales Rank: {{rank.rank}}</td><td>{{rank.rank_date}}</td></tr>
                <tr><td>Current Low Price: ${{price.price}}</td><td>Sell Score: {{score.total_sell_score}}</td><td>My Price: ${{ book.last_ask_price }}</td></tr>
        </table>
        <img src="{% url 'books:book-chart' book.id condition %}" width="400" height="300"/>
    <form action="{% url 'books:list' book.id %}" method="post">
        {% csrf_token %}
        <input type="text" name="Price" id="original_ask_price" value="{{ book.original_ask_price}}" />
        <input type="text" name="Condition" id="list_condition" value="{{ book.list_condition}}" />
        
 
        <input type="submit" value="List" />
        </form>

<ul>

</ul>